name: 'Deploy to GitHub Pages'
description: 'This action will handle the deployment process of your project to GitHub Pages.'
author: 'James Ives <iam@jamesiv.es>'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'git-commit'
  color: 'orange'